name: Greeting

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: 
    -name:
"actions/first-interaction@v1"
      with:
        repo-token: "
        -name:
        "$ghp_0J81ntQaHXMnUrgqH0n72KKV3ZA66a2oq8fF"
        issue-message: "Welcome to the Bay Area's #1 pet groomer's newest Doggy Hotel & Spa! Welcome to Jazzy and Marie's [from the owners of Benny and Sukis]"
        pr-message: "Contact information will be listed below for appointments and FAQ phone:+1(415)724-6197"
